// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yyhvemjyirgaxrkwemde.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl5aHZlbWp5aXJnYXhya3dlbWRlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0NzI5MDUsImV4cCI6MjA2OTA0ODkwNX0.wYOjo6TV2ioZ-HpQXC8YTbGrMIACFDPv8kUrDvayQHs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});